### ISSUE TITLE
Code doesn't compile with version 4 of SDK

### ISSUE THREAD

**Issue by wocbiz** [zenon-network/znn_cli_dart#1]
Within cli_handler.dart:
Line: 137
znnClient.subscribe.toAllAccountEvents() should become:
znnClient.subscribe.toAllAccountBlocks()

and 
Line: 997
znnClient.embedded.token.mint(... should become:
znnClient.embedded.token.mintToken(...

**Comment by av-vonsbak** [comment]
fixed in #2
