### ISSUE TITLE
The command 'wallet.export' should be a command without connection

### ISSUE THREAD

**Issue by KingGorrin** [zenon-network/znn_cli_dart#3]
The 'wallet.export' command requires a connection to a node. The connection is not necessary because it is not used in the command.

The 'wallet.export' command should be added to the `commandsWithoutConnection` list in order to be processed without the connection requirement.

https://github.com/zenon-network/znn_cli_dart/blob/a5c51299278294b4a7c94deda02d111a24c6189c/init_znn.dart#L175

**Comment by sol-znn** [comment]
This will be fixed in v0.0.5 https://github.com/zenon-network/znn_cli_dart/pull/5/commits/4c2ef8b28e2a84a036db16aa95435c025cca3782
